global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "homeassistant"
    metrics_path: /api/prometheus
    scheme: http
    scrape_interval: 30s
    static_configs:
        - targets: ["homeassistant.local:8123"]